package org.frc1410.chargedup2023.util;

public interface IDs {
	int SHOOTER_RIGHT_MOTOR_ID = 52;
	int SHOOTER_LEFT_MOTOR_ID = 44;

	int INTAKE_FRONT_MOTOR_ID = 0;
	int INTAKE_BACK_MOTOR_ID = 0;

	int STORAGE_FRONT_LEFT_MOTOR_ID = 0;
	int STORAGE_FRONT_RIGHT_MOTOR_ID = 0;
	int STORAGE_BACK_LEFT_MOTOR_ID = 0;
	int STORAGE_BACK_RIGHT_MOTOR_ID = 0;


	int INTAKE_LIMIT_SWITCH_ID = 0;

	int DRIVER_CONTROLLER = 0;
	int OPERATOR_CONTROLLER = 1;

}