package org.frc1410.chargedup2023.util;

public interface IDs {

	int LEFT_FRONT_DRIVE_MOTOR = 0;
	int LEFT_FRONT_STEER_MOTOR = 1;
	int RIGHT_FRONT_DRIVE_MOTOR = 2;
	int RIGHT_FRONT_STEER_MOTOR = 3;
	int LEFT_BACK_DRIVE_MOTOR = 4;
	int LEFT_BACK_STEER_MOTOR = 5;
	int RIGHT_BACK_DRIVE_MOTOR = 6;
	int RIGHT_BACK_STEER_MOTOR = 7;

	int LEFT_FRONT_STEER_ENCODER = 0;
	int RIGHT_FRONT_STEER_ENCODER = 1;
	int LEFT_BACK_STEER_ENCODER = 2;
	int RIGHT_BACK_STEER_ENCODER = 3;

}
