package org.frc1410.chargedup2023.util;

public interface IDs {
	int SHOOTER_RIGHT_MOTOR_ID = 52;
	int SHOOTER_LEFT_MOTOR_ID = 44;

	int STORAGE_FRONT_LEFT_MOTOR_ID = 1;
	int STORAGE_FRONT_RIGHT_MOTOR_ID = 2;
	int STORAGE_BACK_LEFT_MOTOR_ID = 3;
	int STORAGE_BACK_RIGHT_MOTOR_ID = 4;
	int STORAGE_UPPER_LIMIT_SWITCH_ID = 5;
	int STORAGE_LOWER_LIMIT_SWITCH_ID = 6;
	int INTAKE_FRONT_MOTOR_ID = 7;
	int INTAKE_BACK_MOTOR_ID = 8;

}