package org.frc1410.crescendo2024.util;

public interface IDs {
	int FRONT_LEFT_DRIVE_MOTOR = 3;
	int FRONT_LEFT_STEER_MOTOR = 4;
	int FRONT_RIGHT_DRIVE_MOTOR = 1;
	int FRONT_RIGHT_STEER_MOTOR = 2;
	int BACK_LEFT_DRIVE_MOTOR = 5;
	int BACK_LEFT_STEER_MOTOR = 6;
	int BACK_RIGHT_DRIVE_MOTOR = 7;
	int BACK_RIGHT_STEER_MOTOR = 8;

	int FRONT_LEFT_STEER_ENCODER = 1;
	int FRONT_RIGHT_STEER_ENCODER = 0;
	int BACK_LEFT_STEER_ENCODER = 2;
	int BACK_RIGHT_STEER_ENCODER = 3;
}